### ISSUE TITLE
Hello there can u pls add asian drama too in this app? This would b great then :))

### ISSUE THREAD

**Issue by Aruraka** [rizalord/samehadaku-app#1]

**Comment by rizalord** [comment]
Hi there,

Thank you for your interest in the Samehadaku app. Unfortunately, the website Samehadaku is no longer operational, and I've discontinued development and maintenance of this app. 

Additionally, the website itself never featured Asian dramas, so adding that functionality was never a possibility.

Thanks for understanding.
